version: '3.9'

services:
  postgres: 
    image: postgres
    restart: always
    container_name: pair_pro_v2
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pgSQL
      - POSTGRES_DB=pair_pro
    volumes:
      - postgres:/data/postgres

volumes:
  postgres: