version: '3.9'

services:
  postgres:
    image: postgres
    restart: always
    container_name: pair_pro_v2
    ports:
      - 5432:5432
    env_file:
      - .env.test.local
    volumes:
      - postgres:/data/postgres

  pgAdmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgAdmin
    ports:
      - "5050:80"
    env_file:
      - .env.test.local

volumes:
  postgres:
